### ISSUE TITLE
[Todo] Blur notifications when pressed

### ISSUE THREAD

**Issue by SlimShadys** [Skittyblock/Dune#10]
### Now, if you long press on a notification, the background it's gonna be black like in the pic attached.

> ![2](https://user-images.githubusercontent.com/6324754/62619410-06bdd000-b917-11e9-9fc7-b66f6ae8532d.PNG)

### Is it possible to make that background blur as in the preview showed below?

> ![1](https://user-images.githubusercontent.com/6324754/62619417-0a515700-b917-11e9-87b2-5bc448330172.PNG)

**Comment by Skittyblock** [comment]
I won't be doing this as the stock light mode has a plain white background and the iOS 13 dark mode has a plain black background.
