### ISSUE TITLE
Request: add Carbon Dark Mode as a related tweak

### ISSUE THREAD

**Issue by rllbe** [Skittyblock/Dune#11]
https://github.com/Skittyblock/Dune/blob/9b1df9790230115b7553cc9dbadf36889018d7f9/Tweak.xm#L26

Could you add Carbon Dark Mode to be automatically enabled when Dune is enabled? 
It can be easily enabled/disabled by the following codes:
```
CFPreferencesSetAppValue((CFStringRef)@"enabled", (CFPropertyListRef)[NSNumber numberWithBool:setOn], CFSTR("com.oxidelabs.carbon"));
notify_post(@"com.oxidelabs.carbon.prefschanged".UTF8String);
```

**Comment by Skittyblock** [comment]
I won't be doing this as Carbon is effectively a replacement of Dune. There's no reason to use them in conjunction.
