### ISSUE TITLE
[Request] Extend blur to Gboard system wide

### ISSUE THREAD

**Issue by drpoutine** [Skittyblock/Dune#13]
I saw there was an option to have the keyboard as dark. Would be nice to have this extend system wide. This is what it looks like in spotlight search

![428DF935-F299-4C41-BBBA-2326FE35C7B1](https://user-images.githubusercontent.com/11738103/64070068-82612300-cc1e-11e9-9f14-04d3ebbbd107.jpeg)

**Comment by Skittyblock** [comment]
I'll probably just stick to the stock keyboard, sorry. Feel free to try doing this yourself or anyone else that wants to though.
