### ISSUE TITLE
[Bug] Website popups broken

### ISSUE THREAD

**Issue by j0lol** [Skittyblock/Dune#16]
![00BA196A-A163-4E0D-B46E-FE0E3108267A](https://user-images.githubusercontent.com/24716467/64870632-96a01980-d63b-11e9-9f50-daeaa4433042.jpeg)
Website popups look like this.
Settings: 
![7CDA57B0-C5FB-4273-8061-ECAF818C89CA](https://user-images.githubusercontent.com/24716467/64870749-c51df480-d63b-11e9-8989-97e7191bf3db.jpeg)

**Comment by Skittyblock** [comment]
Can you double check if Dune is actually the one causing this? It shouldn't be, and it isn't for me.
![0438DE8F-B160-4FB1-A31D-57327CF02481](https://user-images.githubusercontent.com/11185448/64894629-dec13b00-d63f-11e9-9a2c-48c92f7d0a4e.jpeg)

**Comment by j0lol** [comment]
Thats weird, I disabled eclipse to make sure, but I'll try disabling some more tweaks and see if any other tweaks are causing the problem. Thanks!

**Comment by j0lol** [comment]
Ah, sorry, I found the tweak that was causing the issue. Thanks for making such a good dark mode tweak Skitty!

**Comment by Skittyblock** [comment]
👍
