### ISSUE TITLE
[Bug] Many widget labels don't turn white

### ISSUE THREAD

**Issue by RwbyChan** [Skittyblock/Dune#4]
Widget for YTcount shows wrong colors for text and for the app "Klok" it shows white text inside a white box

Screenshots here:
https://cdn.discordapp.com/attachments/148926284913836032/572939181521764353/image0.png

https://media.discordapp.net/attachments/148926284913836032/572939185221009419/image1.png

**Comment by Skittyblock** [comment]
There are a lot of widgets that the text doesn't work with :/

**Comment by RwbyChan** [comment]
Can this be solved? Any help that I can provide for it?

**Comment by Skittyblock** [comment]
It needs some more research. I added the help wanted label because I'm not sure how to do it, and maybe someone else does.

**Comment by Skittyblock** [comment]
I think that most widgets have been fixed with 1.1 - 1.1.2, so I'm closing this.
