### ISSUE TITLE
Keyboards one-finger-typing chevron can be seen on w

### ISSUE THREAD

**Issue by edurur** [Skittyblock/Dune#5]
Cant be seen on white background*. Issue can be solved with changing chevron colour to someting whiter.

**Comment by Skittyblock** [comment]
Screenshot? I'm not sure if this is a Dune issue, as Dune only enables the stock dark keyboard.

**Comment by edurur** [comment]
Well, Dune enables stock keyboard where it doesnt on stock Apple and this enables this little interface bug.
[Screenshot](https://i.ibb.co/g6M98zx/IMG-0255.png)

**Comment by Skittyblock** [comment]
I'm not so sure that that's a bug. It's just that the notes background is so light I guess.
