### ISSUE TITLE
[Bug] Respring loop on iPhone X iOS 12.2

### ISSUE THREAD

**Issue by Tizioincognit0** [Skittyblock/Dune#9]
This new update (1.2.1) caused me, after a reboot, a respring loop. I had to force reboot and jailbreak without tweaks and, finally, downgrade it to 1.2.

**Comment by Skittyblock** [comment]
I'm going to need some more info here. What iOS version are you on? None of the changes from 1.2 to 1.2.1 should warrant a respring loop.

**Comment by Tizioincognit0** [comment]
I said iOS version in the issue title. It's 12.2.

**Comment by Skittyblock** [comment]
Oh, sorry about that. If you disable all your tweaks with iCleaner Pro and upgrade again does it still happen?

**Comment by Tizioincognit0** [comment]
Yes, it does.

**Comment by Skittyblock** [comment]
Ok I really don't know why that would happen. I'm pretty sure I have other people on 12.2 that have used Dune just fine.

Well I recommend updating to 12.4 anyways. It's newer and there's no reason not to.

**Comment by Skittyblock** [comment]
Since I've received no response in a week and I haven't gotten anything that would allow me to find what the issue may be, I'm closing this.

**Comment by Tizioincognit0** [comment]
> Since I've received no response in a week and I haven't gotten anything that would allow me to find what the issue may be, I'm closing this.

That's because I've finally update to iOS 13.4.1 so I don't use Dune anymore.
